version: '3'
services:
  server:
    build:
      context: .
      dockerfile: 'Dockerfile'
    env_file:
      - ./.env
    depends_on:
      - mongo
    ports:
      - 4000:4000
  mongo:
    image: mongo
    env_file:
      - ./.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
