version: '3'
services:
  server:
    build:
      context: './server'
      dockerfile: 'Dockerfile'
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    ports:
      - 4000:4000
    volumes:
      - ./server:/server
      - /server/node_modules
  mongo:
    image: mongo
    env_file:
      - ./server/.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: