export const workingDays = [
  {
    date: new Date('Mon Jan 25 2021 19:50:52 GMT+0100'),
    workingFromHome: true,
    meansOfTransport: 'train',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    roundTrip: true,
    durationTripOne: 0,
    durationTripTwo: 0,
    costs: 0.0,
  },
  {
    date: new Date('Tue Jan 26 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 90,
    durationTripTwo: 40,
    costs: 24.99,
  },
  {
    date: new Date('Wed Jan 27 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 85,
    durationTripTwo: 85,
    costs: 24.99,
  },
  {
    date: new Date('Thu Jan 28 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 99999,
    durationTripTwo: 0,
    costs: 24.99,
  },
  {
    date: new Date('Fri Jan 29 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'train',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    roundTrip: false,
    durationTripOne: 150,
    durationTripTwo: 150,
    costs: 24.99,
  },
  {
    date: new Date('Mon Feb 1 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'train',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    roundTrip: true,
    durationTripOne: 150,
    durationTripTwo: 150,
    costs: 24.99,
  },
  {
    date: new Date('Tue Feb 2 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 90,
    durationTripTwo: 35,
    costs: 24.99,
  },
  {
    date: new Date('Wed Feb 3 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 85,
    durationTripTwo: 85,
    costs: 24.99,
  },
  {
    date: new Date('Thu Feb 4 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'train',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 150,
    durationTripTwo: 150,
    costs: 24.99,
  },
  {
    date: new Date('Fri Feb 5 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'train',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    roundTrip: false,
    durationTripOne: 150,
    durationTripTwo: 150,
    costs: 24.99,
  },
  {
    date: new Date('Mon Feb 8 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'train',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    roundTrip: true,
    durationTripOne: 150,
    durationTripTwo: 150,
    costs: 24.99,
  },
  {
    date: new Date('Tue Feb 9 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 90,
    durationTripTwo: 35,
    costs: 24.99,
  },
  {
    date: new Date('Wed Feb 10 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 85,
    durationTripTwo: 85,
    costs: 24.99,
  },
  {
    date: new Date('Thu Feb 11 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 35,
    durationTripTwo: 35,
    costs: 24.99,
  },
  {
    date: new Date('Fri Feb 12 2021 19:50:52 GMT+0100'),
    workingFromHome: true,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    roundTrip: false,
    durationTripOne: 0,
    durationTripTwo: 0,
    costs: 24.99,
  },
  {
    date: new Date('Mon Feb 15 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'train',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    roundTrip: true,
    durationTripOne: 150,
    durationTripTwo: 150,
    costs: 24.99,
  },
  {
    date: new Date('Tue Feb 16 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 90,
    durationTripTwo: 35,
    costs: 24.99,
  },
  {
    date: new Date('Wed Feb 17 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 35,
    durationTripTwo: 35,
    costs: 24.99,
  },
  {
    date: new Date('Thu Feb 18 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 35,
    durationTripTwo: 35,
    costs: 24.99,
  },
  {
    date: new Date('Fri Feb 19 2021 19:50:52 GMT+0100'),
    workingFromHome: true,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    roundTrip: false,
    durationTripOne: 0,
    durationTripTwo: 0,
    costs: 24.99,
  },
];

export const week1 = [
  {
    date: new Date('Mon Feb 8 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'train',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    roundTrip: true,
    durationTripOne: 150,
    durationTripTwo: 150,
    costs: 24.99,
  },
  {
    date: new Date('Tue Feb 9 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 90,
    durationTripTwo: 35,
    costs: 24.99,
  },
  {
    date: new Date('Wed Feb 10 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 35,
    durationTripTwo: 35,
    costs: 24.99,
  },
  {
    date: new Date('Thu Feb 11 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    roundTrip: false,
    durationTripOne: 35,
    durationTripTwo: 35,
    costs: 24.99,
  },
  {
    date: new Date('Fri Feb 12 2021 19:50:52 GMT+0100'),
    workingFromHome: false,
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    roundTrip: false,
    durationTripOne: 35,
    durationTripTwo: 95,
    costs: 24.99,
  },
];
