export const workingDays = [
  {
    date: new Date('Mon Jan 18 2021 19:50:52 GMT+0100'),
    statusOfDay: 'day off',
  },
  {
    date: new Date('Tue Jan 19 2021 19:50:52 GMT+0100'),
    statusOfDay: 'day off',
  },
  {
    date: new Date('Wed Jan 20 2021 19:50:52 GMT+0100'),
    statusOfDay: 'day off',
  },
  {
    date: new Date('Thu Jan 21 2021 19:50:52 GMT+0100'),
    statusOfDay: 'day off',
  },
  {
    date: new Date('Fri Jan 22 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'public transport',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    durationTripOne: 150,
    durationTripTwo: 150,
  },
  {
    date: new Date('Mon Jan 25 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'public transport',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    durationTripOne: 150,
    durationTripTwo: 150,
  },
  {
    date: new Date('Tue Jan 26 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 150,
    durationTripTwo: 35,
  },
  {
    date: new Date('Wed Jan 27 2021 19:50:52 GMT+0100'),
    statusOfDay: 'day off',
  },
  {
    date: new Date('Thu Jan 28 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working from home',
  },
  {
    date: new Date('Fri Jan 29 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'public transport',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    durationTripOne: 150,
    durationTripTwo: 150,
  },
  {
    date: new Date('Mon Feb 1 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working from home',
  },
  {
    date: new Date('Tue Feb 2 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 90,
    durationTripTwo: 35,
  },
  {
    date: new Date('Wed Feb 3 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 85,
    durationTripTwo: 25,
  },
  {
    date: new Date('Thu Feb 4 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working from home',
  },
  {
    date: new Date('Fri Feb 5 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'public transport',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    durationTripOne: 150,
    durationTripTwo: 150,
  },
  {
    date: new Date('Mon Feb 8 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'public transport',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    durationTripOne: 150,
    durationTripTwo: 150,
  },
  {
    date: new Date('Tue Feb 9 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 90,
    durationTripTwo: 35,
  },
  {
    date: new Date('Wed Feb 10 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 85,
    durationTripTwo: 85,
  },
  {
    date: new Date('Thu Feb 11 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 135,
    durationTripTwo: 135,
  },
  {
    date: new Date('Fri Feb 12 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    durationTripOne: 35,
    durationTripTwo: 35,
  },
  {
    date: new Date('Mon Feb 15 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'public transport',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    durationTripOne: 150,
    durationTripTwo: 150,
  },
  {
    date: new Date('Tue Feb 16 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 90,
    durationTripTwo: 35,
  },
  {
    date: new Date('Wed Feb 17 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 35,
    durationTripTwo: 35,
  },
  {
    date: new Date('Thu Feb 18 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 35,
    durationTripTwo: 35,
  },
  {
    date: new Date('Fri Feb 19 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    durationTripOne: 35,
    durationTripTwo: 35,
  },
  {
    date: new Date('Mon Feb 22 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    durationTripOne: 150,
    durationTripTwo: 150,
  },
  {
    date: new Date('Tue Feb 23 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Tilburg - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 90,
    durationTripTwo: 150,
  },
  {
    date: new Date('Wed Feb 24 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 35,
    durationTripTwo: 35,
  },
  {
    date: new Date('Thu Feb 25 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Terneuzen',
    durationTripOne: 135,
    durationTripTwo: 135,
  },
  {
    date: new Date('Fri Feb 26 2021 19:50:52 GMT+0100'),
    statusOfDay: 'working at the office',
    meansOfTransport: 'car',
    routeTripOne: 'Terneuzen - Vlissingen',
    routeTripTwo: 'Vlissingen - Tilburg',
    durationTripOne: 50,
    durationTripTwo: 20,
  },
];
